"Machine Learning 1: Grundlagen und statistische Lerntheorie":
  - "/ml-1/i"
"Machine Learning 2: Deep Learning":
  - "/ml-2/i"
"Stochastik 1":
  - "/sto-1/i"
"Stochastik 2":
  - "/sto-2/i"
"Maß- und Integrationstheorie":
  - "/muit/i"
"Natural Language Processing":
  - "/nlp/i"
"Numerik für Maschinelles Lernen":
  - "/num-ml/i"

"AMI M. Sc.":
  - "/(ml-1|ml-2|sto-1|sto-2|muit|nlp|num-ml)/i"

"Wahlmodul (M. Sc.)":
  - "/(ml-1|ml-2|sto-1|sto-2|muit|nlp|num-ml)/i"

"Zettel":
  - "/zettel/i"

"Assignment":
  - "/(assignment|uebung|übung|blatt|sheet)/i"

"Module / Section":
  - "/(vorlesung|lecture|module|section|modul|kapitel|chapter)/i"
